### ISSUE TITLE
Specify arrow keys behavior while chooser is open?

### ISSUE THREAD

**Issue by ericlaw1979** [WICG/eyedropper-api#16]
With the current Chromium prototype on my 4k screen, it's impossible to select some pixels because the touchpad sensitivity is insufficient. 

In most screengrabber applications, the user can use the arrow keys to move the selected pixel by a single pixel at a time. Perhaps this new feature should have that behavior as well?

**Comment by ipopescu93** [comment]
Thanks for the issue! The user agent has the freedom to implement eyedropper pixel selection UI that bests fits their platform and follows these [rules](https://wicg.github.io/eyedropper-api/#eyedropper).

For the Chromium implementation we are using this [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1141519) to track adding keyboard support.
