### ISSUE TITLE
Should sRGBHex be readonly

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [WICG/eyedropper-api#2]
If not readonly, should sRGBHex define [setter](https://heycam.github.io/webidl/#setter-steps) and [getter steps](https://heycam.github.io/webidl/#getter-steps)?

**Comment by ipopescu93** [comment]
I think it is enough to guarantee that colorSelectionResult.sRGBHex returned by EyeDropper.open() is a [valid simple color](https://html.spec.whatwg.org/multipage/#valid-simple-colour).
