### ISSUE TITLE
Under security and privacy should you describe how double click attacks will be mitigated

### ISSUE THREAD

**Issue by BoCupp-Microsoft** [WICG/eyedropper-api#5]
During a security review a double-click attack was discussed where the first click enters the eyedropper mode and the second click captures a pixel.  This is problematic if it happens fast so that the user is never aware that a pixel was captured.  I believe this is mitigated by introducing a requirement that the eyedropper UI must be displaying before a color can be sampled and having a minimum time after the click to display the eyedropper before it can be used to sample a color.  Can you add something about this to the security section?

**Comment by ipopescu93** [comment]
I added a comment in the security section explaining how browsers can ensure that the UI was visible before allowing color selection.
