### ISSUE TITLE
Mouse event to the page while eyedropper is open

### ISSUE THREAD

**Issue by upsuper** [WICG/eyedropper-api#7]
While testing the eyedropper in Canva, I noticed that the mouse event sometimes leaks to the page when the mouse moves fast enough, which causes some hovering UI to show up briefly, see:

https://user-images.githubusercontent.com/333750/129501389-41dd9ff3-db80-4481-9f9b-ca5644a297fb.mp4

This itself is probably a impl issue, but I think it's probably worth mentioning in the spec that the page shouldn't be getting the mouse event when eyedropper is open?

**Comment by ipopescu93** [comment]
Thanks for the issue! This is indeed an implementation issue that needs to be addressed.

In the [spec](https://wicg.github.io/eyedropper-api/#dom-eyedropper-open) it is specified that while in "eyedropper mode", the user input is suppressed: no UI events are dispatched to the web page.
